version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 task_manager.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True